### ISSUE TITLE
Open sources

### ISSUE THREAD

**Issue by mattfaluotico** [syn-ack-zack/ProjectBookup#16]
Can we open source this, dude?

**Comment by kroppian** [comment]
Yeah sure haha!

On Tue, Jun 17, 2014 at 9:10 PM, Matthew Faluotico <notifications@github.com

**Comment by syn-ack-zack** [comment]
sure thing, I can make this public if you'd like. If we want to fully open source it we will need to pick a license and mark up all our source files. Here is a site that discusses this a bit since I haven't done this before. 

http://oss-watch.ac.uk/resources/opensourceyourcode

Also, are we good on any academic misconduct for doing this?

I'll look into this more tomorrow, but I just got home and I am heading to bed. Hope you guys have had a good summer so far!
